### ISSUE TITLE
ObservableDictionary does not set shouldRaiseNotifications and wrong PropertyChangedEventArgs are used

### ISSUE THREAD

**Issue by randomt4sk** [xamarinhq/xamu-infrastructure#16]
Hello,

I ran into two problems with your ObservableDictionary class.

The bool "shouldRaiseNotifications" is never set to true (except in the "MassUpdater").
Therefore the UI was not notified.
There is no way to set this value from outside of the class.

Also in the "OnPropertyChanged" calls the PropertyChangedEventArgs are initialized with the key of the corresponding item. This causes the UI to not be updated.
I had to set it to "Item[" + item.Key.ToString()+ "]" in order to make it work.

I do not know if this problem only occurs in my setup or if it is a general problem.
Let me know if you need further information or if I did not use the class correctly.

Best regards

**Comment by markjulmar** [comment]
Ah, you are correct. We were only using it with `MassUpdate`. I have added unit tests and fixed the issue so it should be working correctly for you now. Please use *2.1** from Nuget.

**Comment by markjulmar** [comment]
Regarding the `PropertyChangedEventArgs`, it's working the way I expect it to - it should send an updat e for`Count` and the `Key`. Really nothing in Forms should even be looking at that - this is really for collection binding, not individual properties. How are you using the dictionary - e.g. what is the binding that is using it?

Here's how you _could_ use it with a specific property - like an Entry:

```
<Entry Text="{Binding Source=dictionary, Path=Name, Mode=OneWay}" />
...
dictionary["Name"] = "Mark"; // would update the Entry
...
```

Does that help?

**Comment by randomt4sk** [comment]
Thanks alot for the instant fix.
However, the other problem still exists.
I quickly tested your code snippet without success.

In the following you can see my sample code.

MainPage.xaml:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:X_ME"
             x:Class="X_ME.MainPage">

    <StackLayout x:Name="_mainLayout">
        <Button Text="Show Value" Clicked="Show_Button_Clicked" />
        <Button Text="Change Value" Clicked="Change_Button_Clicked" />
    </StackLayout>

</ContentPage>
```

MainPage.xaml.cs:
```
using System.ComponentModel;
using Xamarin.Forms;
using XamarinUniversity.Infrastructure;

namespace X_ME
{

    public partial class MainPage : ContentPage
    {

        private ObservableDictionary<string, string> _dict;

        public MainPage()
        {

            InitializeComponent();

            _dict = new ObservableDictionary<string, string>
            {
                { "test", "foo" }
            };

            this.BindingContext = _dict;

            var entry = new Entry();
            entry.SetBinding(Entry.TextProperty, "[test]");
            _mainLayout.Children.Add(entry);

        }


        private void Show_Button_Clicked(object sender, System.EventArgs e)
        {
            DisplayAlert("Value of 'test'", _dict["test"], "OK");
        }

        private void Change_Button_Clicked(object sender, System.EventArgs e)
        {
            _dict["test"] = "bar";
        }

    }
}
```

I'm trying to get a twoway binding, which causes the UI to update if a value of a dictionary entry is changed and vice versa,
If i click the Update-button and the Show-button afterwards, the alert shows the new value ("bar").
The UI doesn't reflect this.

However, if I change the PropertyChangedEventArgs it works.
Example:
OnPropertyChanged(new PropertyChangedEventArgs("test"));
-> UI does not update
OnPropertyChanged(new PropertyChangedEventArgs("Item[test]"));
-> UI updates

Sorry if I use you class incorrectly, but I'm new to app development.

**Comment by markjulmar** [comment]
Dangit. You're right. I even say this in the forums way back in 2014. https://forums.xamarin.com/discussion/19361/data-binding-to-dictionary-object

We are using this in a different way - so not trying to bind to individual values. I'll push up a 2.1.1 Core here and make sure there's a unit test.

Thanks!

**Comment by randomt4sk** [comment]
Thanks again for the instant fix!

It works like a charm now.
